-- =====================================================================================
-- Raqib | 08 GOVERNANCE: PII classification tags, masking, least-privilege grants
-- Analysts investigate with masked identifiers; the MLRO sees full PII and alone can
-- read filed STRs. Ground-truth test data is visible to the platform owner only.
-- =====================================================================================
USE ROLE RAQIB_ADMIN;
USE WAREHOUSE RAQIB_WH;

CREATE TAG IF NOT EXISTS RAQIB.OPS.PII_TYPE
  ALLOWED_VALUES 'NATIONAL_ID', 'PHONE', 'EMAIL', 'DATE_OF_BIRTH', 'ACCOUNT_NUMBER'
  COMMENT = 'Personal data classification';

-- Masking: full value for MLRO / admin, partial for everyone else
CREATE OR REPLACE MASKING POLICY RAQIB.OPS.MASK_PII_STRING AS (val VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN val IS NULL THEN NULL
    WHEN IS_ROLE_IN_SESSION('RAQIB_MLRO') THEN val
    ELSE REPEAT('*', GREATEST(LENGTH(val) - 4, 0)) || RIGHT(val, 4)
  END
  COMMENT = 'Shows last 4 characters unless the MLRO role is active';

CREATE OR REPLACE MASKING POLICY RAQIB.OPS.MASK_DOB AS (val DATE) RETURNS DATE ->
  CASE WHEN IS_ROLE_IN_SESSION('RAQIB_MLRO') THEN val ELSE DATE_TRUNC('year', val) END
  COMMENT = 'Analysts see year of birth only';

-- Tag-based classification + masking on the source and on the 360 profile
ALTER TABLE RAQIB.RAW.CUSTOMERS MODIFY
    COLUMN EMIRATES_ID   SET TAG RAQIB.OPS.PII_TYPE = 'NATIONAL_ID',
    COLUMN PHONE         SET TAG RAQIB.OPS.PII_TYPE = 'PHONE',
    COLUMN EMAIL         SET TAG RAQIB.OPS.PII_TYPE = 'EMAIL',
    COLUMN DATE_OF_BIRTH SET TAG RAQIB.OPS.PII_TYPE = 'DATE_OF_BIRTH';
ALTER TABLE RAQIB.RAW.CUSTOMERS MODIFY COLUMN EMIRATES_ID   SET MASKING POLICY RAQIB.OPS.MASK_PII_STRING;
ALTER TABLE RAQIB.RAW.CUSTOMERS MODIFY COLUMN PHONE         SET MASKING POLICY RAQIB.OPS.MASK_PII_STRING;
ALTER TABLE RAQIB.RAW.CUSTOMERS MODIFY COLUMN EMAIL         SET MASKING POLICY RAQIB.OPS.MASK_PII_STRING;
ALTER TABLE RAQIB.RAW.CUSTOMERS MODIFY COLUMN DATE_OF_BIRTH SET MASKING POLICY RAQIB.OPS.MASK_DOB;
ALTER TABLE RAQIB.RAW.ACCOUNTS  MODIFY COLUMN IBAN SET TAG RAQIB.OPS.PII_TYPE = 'ACCOUNT_NUMBER';

ALTER DYNAMIC TABLE RAQIB.CORE.CUSTOMER_PROFILE MODIFY COLUMN EMIRATES_ID   SET MASKING POLICY RAQIB.OPS.MASK_PII_STRING;
ALTER DYNAMIC TABLE RAQIB.CORE.CUSTOMER_PROFILE MODIFY COLUMN PHONE         SET MASKING POLICY RAQIB.OPS.MASK_PII_STRING;
ALTER DYNAMIC TABLE RAQIB.CORE.CUSTOMER_PROFILE MODIFY COLUMN EMAIL         SET MASKING POLICY RAQIB.OPS.MASK_PII_STRING;
ALTER DYNAMIC TABLE RAQIB.CORE.CUSTOMER_PROFILE MODIFY COLUMN DATE_OF_BIRTH SET MASKING POLICY RAQIB.OPS.MASK_DOB;

-- ---------------------------------------------------------------------------------
-- Least-privilege grants
-- ---------------------------------------------------------------------------------
-- Analyst: read the governed analytical layers, act only through tools
GRANT SELECT ON ALL TABLES          IN SCHEMA RAQIB.CORE   TO ROLE RAQIB_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES  IN SCHEMA RAQIB.CORE   TO ROLE RAQIB_ANALYST;
GRANT SELECT ON ALL VIEWS           IN SCHEMA RAQIB.CORE   TO ROLE RAQIB_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES  IN SCHEMA RAQIB.DETECT TO ROLE RAQIB_ANALYST;
GRANT SELECT ON ALL VIEWS           IN SCHEMA RAQIB.DETECT TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.DETECT.RULE_CATALOG           TO ROLE RAQIB_ANALYST;
GRANT SELECT ON ALL VIEWS           IN SCHEMA RAQIB.RISK   TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.DOCS.POLICY_CHUNKS            TO ROLE RAQIB_ANALYST;
GRANT SELECT ON VIEW  RAQIB.DOCS.DOCUMENT_CATALOG         TO ROLE RAQIB_ANALYST;
GRANT USAGE  ON CORTEX SEARCH SERVICE RAQIB.DOCS.POLICY_SEARCH TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.RAW.CUSTOMERS      TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.RAW.ACCOUNTS       TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.RAW.TRANSACTIONS   TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.RAW.COUNTERPARTIES TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.RAW.LOANS          TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.RAW.COUNTRY_RISK   TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.RAW.WATCHLIST      TO ROLE RAQIB_ANALYST;
-- NOTE: RAW.PLANTED_CASES (ground truth) is intentionally NOT granted.

GRANT SELECT ON VIEW  RAQIB.OPS.ALERT_QUEUE    TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.OPS.CASES          TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.OPS.CASE_ALERTS    TO ROLE RAQIB_ANALYST;
GRANT SELECT ON TABLE RAQIB.OPS.ALERT_WORKFLOW TO ROLE RAQIB_ANALYST;
GRANT INSERT ON TABLE RAQIB.OPS.COPILOT_AUDIT  TO ROLE RAQIB_ANALYST;
GRANT USAGE ON PROCEDURE RAQIB.OPS.GET_ALERT_EVIDENCE(VARCHAR)                   TO ROLE RAQIB_ANALYST;
GRANT USAGE ON PROCEDURE RAQIB.OPS.GET_CUSTOMER_360(VARCHAR)                     TO ROLE RAQIB_ANALYST;
GRANT USAGE ON PROCEDURE RAQIB.OPS.UPDATE_ALERT_STATUS(VARCHAR, VARCHAR, VARCHAR) TO ROLE RAQIB_ANALYST;
GRANT USAGE ON PROCEDURE RAQIB.OPS.CREATE_CASE(VARCHAR, VARCHAR)                 TO ROLE RAQIB_ANALYST;
GRANT USAGE ON PROCEDURE RAQIB.OPS.DRAFT_STR(VARCHAR)                            TO ROLE RAQIB_ANALYST;
GRANT USAGE ON PROCEDURE RAQIB.OPS.GENERATE_REGULATORY_REPORT(VARCHAR)           TO ROLE RAQIB_ANALYST;

-- MLRO: reports (STRs are confidential), audit trail, and the approval tool (caller's rights)
GRANT SELECT, UPDATE ON TABLE RAQIB.OPS.REPORTS TO ROLE RAQIB_MLRO;
GRANT SELECT, UPDATE ON TABLE RAQIB.OPS.CASES TO ROLE RAQIB_MLRO;
GRANT SELECT, UPDATE ON TABLE RAQIB.OPS.ALERT_WORKFLOW TO ROLE RAQIB_MLRO;
GRANT SELECT, INSERT ON TABLE RAQIB.OPS.AUDIT_LOG TO ROLE RAQIB_MLRO;
GRANT SELECT ON TABLE RAQIB.OPS.COPILOT_AUDIT TO ROLE RAQIB_MLRO;
GRANT SELECT ON TABLE RAQIB.OPS.SETTINGS TO ROLE RAQIB_MLRO;
GRANT USAGE ON PROCEDURE RAQIB.OPS.APPROVE_REPORT(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE RAQIB_MLRO;

-- ---------------------------------------------------------------------------------
-- Governance verification (run in CoCo testing phase)
-- ---------------------------------------------------------------------------------
USE ROLE RAQIB_ANALYST;
SELECT CUSTOMER_ID, EMIRATES_ID, PHONE, DATE_OF_BIRTH FROM RAQIB.CORE.CUSTOMER_PROFILE LIMIT 3;  -- masked
USE ROLE RAQIB_MLRO;
SELECT CUSTOMER_ID, EMIRATES_ID, PHONE, DATE_OF_BIRTH FROM RAQIB.CORE.CUSTOMER_PROFILE LIMIT 3;  -- clear
USE ROLE RAQIB_ADMIN;
